language: java
sudo: false
jdk:
- openjdk8
dist: trusty

addons:
  sonarcloud:
    organization: "growthcraftce"
    token:
      secure: "0dff37f87344985cef77db78d7736b3792bfbdc1"

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.sonar/cache
  - $HOME/.m2/repositor
  - .gradle

before_install:
# ensure we have ruby
- ruby --version
- chmod +x ./gradlew

install: ./gradlew setupCIWorkspace -S

script:
- ./gradlew build
- sonar-scanner
- ls -la build/libs

git:
  depth: false

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file_glob: true
  file:
  - "checksums.txt"
  - "build/libs/growthcraft-*.jar"
  skip_cleanup: true
  on:
    tags: true