name: Growthcraft Tagged Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

jobs:
  build:

    name: Build Growthcraft
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8     
    - name: Setup Gradle
      run: chmod +x gradlew
    - name: Setup CI Workspace
      run:  ./gradlew setupCIWorkspace
    - name: Build with Gradle
      run: ./gradlew build  
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: Run sonarqube
      env:
        # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
             -Dsonar.organization=growthcraftce
             -Dsonar.host.url=https://sonarcloud.io/
             -Dsonar.projectKey=growthcraft:Growthcraft-1.12
        
  release:
    
    name: Release on Tag
    runs-on: ubuntu-latest
    
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: build/libs/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
